/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gilded.rose.refactoring.kata;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
